appCastEdu/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'users/perfil/:id' => 'users#get_perfil', as: 'perfil'
  post 'users/profile' => 'users#login', as: 'login'

  get 'room/:id/forum/new' => 'forums#new', as: 'forum'
  post 'room/:id/forum/create' =>'rooms#create_forum', as: 'create_forum'

  match 'auth/:provider/callback' => 'users#register', as: 'register', via: [:get, :post]

  get 'login/' => 'users#index', as: 'make_login'

  post 'users/perfil/:id/create_room'=> 'users#create_room', as: 'create_room'

  resources :admins
  resources :contributors
  resources :comments
  resources :categories

  resources :users

  get  'users/login/:email'  => 'users#login', :constraints => { :email => /[^\/]+/ }
  post 'users/login/:email'  => 'users#login', :constraints => { :email => /[^\/]+/ }
  post 'password_reset/create' => 'password_reset#create'
  get  'password_reset/:key/edit'  => 'password_reset#edit', :constraints => { :email => /[^\/]+/ }
  patch  'password_reset/:key' => 'password_reset#update'

end

appCastEdu/app/models/admin.rb
class Admin < ActiveRecord::Base
end

appCastEdu/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :rooms
end

appCastEdu/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to: entity_colab, :as => :childrenable

end

appCastEdu/app/models/contributor.rb
class Contributor < ActiveRecord::Base
end

appCastEdu/app/models/entity_colab.rb
class EntityColab < ActiveRecord::Base

  has_and_belongs_to_many :children,
      :class_name => "EntityColab",
      :join_table => "children_containers",
      :foreign_key => "container_id",
      :association_foreign_key => "child_id"

    has_and_belongs_to_many :containers,
      :class_name => "EntityColab",
      :join_table => "children_containers",
      :foreign_key => "child_id",
      :association_foreign_key => "container_id"

    def root?
      self.containers.empty?
    end

    def leaf?
      self.children.empty?
    end

    def to_s(level=0)
      "#{'  ' * level}#{name}\n" + children.map {|c| c.to_s(level + 1)}.join
    end


end

appCastEdu/app/models/forum.rb
require "observer"


class Forum < ActiveRecord::Base
    include Observable

    
  belongs_to: entity_colab, :as => :childrenable

  attr_reader :tittle, :description, :room_id, :erros, :forum
  belongs_to :room
  after_initialize :start

  def start
      puts "Inicializando um Forum"
  end

end

appCastEdu/app/models/forum_builder.rb
class ForumBuilder

  attr_reader :tittle, :description, :room

  def initialize room
      if room.class.to_s != 'Room'
          raise StandardError, "Raising standard error"
        end
      @room = room
      @tittle =  'Titulo em Branco'
      @description = 'Insira uma descrição'
  end

  def build_forum
    Forum.new(tittle: @tittle,description: @description, room_id: @room.id).save
  end

  def com_tittle(tittle)
      @tittle = tittle
    self
  end

  def com_description(description)
      @description = description
      self
  end
end

appCastEdu/app/models/room.rb
require "observer"

class Room < ActiveRecord::Base
  include Observable

  has_many: entity_colab, :as => :childrenable
  has_and_belongs_to_many :components


  attr_accessible :tittle, :description,:id,:user_id
  belongs_to :user

    def create_forum
     ForumBuilder.new(self).build_forum
     notify_observer("um novo forum criado ");
    end

   def create_forum tittle, description
     forum =  ForumBuilder.new(self).com_tittle(tittle).com_description(description)
     forum.build_forum
   end

   def feed_users user
     this.add_observer(user)
   end



end

appCastEdu/app/models/room_builder.rb
class RoomBuilder

  attr_reader :tittle, :description, :user

  def initialize user

      if user.class.to_s != 'User'
          raise StandardError, "Raising standard error"
        end
      @user = user
      @tittle =  'Titulo em Branco'
      @description = 'Insira uma descrição'
  end

  def build_room
    puts @user
    room = Room.new(tittle: @tittle,description: @description,user_id: @user.id)
    room.save
  end

  def com_tittle(tittle)
      @tittle = tittle
    self
  end

  def com_description(description)
      @description = description
      self
  end





end

appCastEdu/app/models/session.rb
class Session
  #construtor
  include Singleton

  def _dump(depth)
    # this strips the @strip information from the instance
    Marshal.dump(@keep, depth)
  end

  def self._load(str)
    instance.keep = Marshal.load(str)
    instance
  end


  def initialize session_type,user
    if session_type == "email"
      @session = SessionEmail.new(user)
    else
        @session = SessionSocial.new(user)
    end
        @session.session
        @user = @session.session_user
  end

  def session_user
    @user
  end

  # Metodo Abstrato
  def session
    raise NotImplementedError
  end

end

appCastEdu/app/models/session_email.rb
class SessionEmail < Session

  def initialize user
      @user = user
  end

  def session
    @user.save
    @user = User.find_by_email(session_user.email);
  end

end

appCastEdu/app/models/session_social.rb
class SessionSocial < Session

  def initialize user
      @user = user
  end

  def session
    user = User.new()
      user.email = @user.info.email
      user.name = @user.info.name
      user.password = @user.uid
      user.save
      @user = User.find_by_email(session_user.info.email);
    end
end

appCastEdu/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :idRedeSocial, :id
  has_secure_password
  has_secure_token
  has_many :rooms
   attr_accessible :register
   attr_accessor :register

  validates :email,
            :on => :create,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }

  def register_strategy strategy,user
      Session.new(strategy,user).session_user
  end

  def create_room
    RoomBuilder.new(self).build_room()
  end


end

appCastEdu/app/controllers/users_controller.rb
class UsersController < ApplicationController

skip_before_filter :verify_authenticity_token, :only => [:update]


  def get_perfil
      @user =  User.find(params[:id]);
      @rooms = Room.where(user_id: params[:id])
  end

    def new
      @users = User.all
    end


  def register
      strategy =  params[:provider]
      if strategy == "email"
        user = User.new(params[:user])
        @user = user.register_strategy(strategy,user)
        redirect_to perfil_path @user
      else
        redirect_to perfil_path  User.new.register_strategy(strategy,get_data_social)
      end
 end

 def get_data_social
   env["omniauth.auth"]
 end


 def login
    user = User.find_by_email user_params[:email]
    puts 'login'
   if !user.blank?
       puts "Pesquisa"
       redirect_to perfil_path user
   else
       puts "Pesquisa1"
       redirect_to login_path
   end
 end



 def create_room
    User.find(params[:id]).create_room
    redirect_to perfil_path params[:id]
 end


  def show
    render json: User.all

  end


    private
     def user_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation , :sex)
     end

    private
    def login_params
      params.require(:user).permit(:email)
    end

    private
    def pefil_params
      params.require(:user).permit(:id)
    end

end

appCastEdu/app/helpers/admins_helper.rb
module AdminsHelper
end

appCastEdu/app/helpers/application_helper.rb
module ApplicationHelper
end

appCastEdu/app/helpers/categories_helper.rb
module CategoriesHelper
end

appCastEdu/app/helpers/comments_helper.rb
module CommentsHelper
end

appCastEdu/app/helpers/contributors_helper.rb
module ContributorsHelper
end

appCastEdu/app/helpers/forums_helper.rb
module ForumsHelper
end

appCastEdu/app/helpers/login_helper.rb
module LoginHelper
end

appCastEdu/app/helpers/rooms_helper.rb
module RoomsHelper
end

appCastEdu/app/helpers/users_helper.rb
module UsersHelper
end

appCastEdu/app/views/users/_form.html.erb
<div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Registrar Uma nova Sala</span>


          <%= form_for(@room) do |f| %>

          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :tittle, :class => 'validate',:type=>"text" %>
              <label for="text">Titulo</label>
            </div>
          </div>



            <div class="row">
              <div class="input-field col s12">
                <%= f.text_area :description, :class => 'validate materialize-textarea',:type=>"text" %>
                  <label for="textarea1">Descrição</label>
              </div>
            </div>

            <div class="actions">
              <%= f.submit "Registrar", :class=>"waves-effect waves-light btn-large" %>
            </div>

            <div class="input-field col s">

                <label>Genero</label>
              </div>
            </div>




          <% end %>



        </div>
      </div>
    </div>
  </div>

appCastEdu/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>
<%= @user %>

appCastEdu/app/views/users/index.html.erb
<div class="row ">
     <div class="col s12 m4 l8 centerAlign ">
       <div class="card-panel">

    <%= form_for :user ,as: :post,  url: login_path do |f|  %>

         <div class="row">
           <div class="input-field col s12">
             <%= f.text_field :email, :class => 'validate',:type=>"email"%>
          <label for="email">Email</label>
           </div>
         </div>

      <div class="row">
        <div class="input-field col s12">
            <%= f.text_field :password, :class => 'validate',:type=>"password"%>
          <label for="password">Password</label>
        </div>
      </div>
      <a class="waves-effect waves-light btn-large"><i class="material-icons left"></i>Voltar</a>
      <%= f.submit "Logar", :class=>"waves-effect waves-light btn-large" %>

<% end %>

<%= button_to "Logar com Facebook", "/auth/facebook", id: "sign_in", :class=>"waves-effect blue darken-4 btn-large"%>
<%= button_to "Logar com Github", "/auth/github", :class=>"waves-effect black darken-4 btn-large"%>
<%= button_to "Logar com GMail", "/auth/google_oauth2",  :class=>"waves-effect  red darken-1 btn-large"%>



    </div>
  </div>
 </div>

appCastEdu/app/views/users/login.html.erb
<!-- Apenas existe para suprir os erros de template do rails  -->

appCastEdu/app/views/users/new.html.erb
<script>

$(document).ready(function() {
   $('select').material_select();
 });

</script>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

  <div class="row">


    <div class="col s12 m6">
      <div class="card light-blue darken-3">
        <div class="card-content white-text">
          <span class="card-title">Registro de uma novo Usuário</span>

      <%= form_for :user ,as: :post,  url: register_path('email') do |f|  %>


          <div class="row">
              <form class="col s12">
                <div class="row">
                  <div class="input-field col s6">
                     <%= f.text_field :name, :class => 'validate',:type=>"text"%>
                    <label for="first_name">Nome </label>
                  </div>

              <div class="input-field col s6">
              <%= f.select "sex", "<option>Homem</option><option>Mulher</option><option>Outro</option>".html_safe%>
                  <label>Genero</label>
                </div>
              </div>


                <div class="row">
                  <div class="input-field col s12">
                   <%= f.text_field :email, :class => 'validate',:type=>"email"%>
                    <label for="email">Email</label>
                  </div>
                </div>

                <div class="row">
                  <div class="input-field col s6">
                     <%= f.text_field :password, :class => 'validate',:type=>"password"%>
                  <label for="password">Password</label>
                  </div>

                  <div class="input-field col s6">
                     <%= f.text_field :password_confirmation, :class => 'validate',:type=>"password"%>
                  <label for="password">Confirmação do Password</label>
                  </div>
                </div>

                <div >
                  <div class="input-field col s6 left-align">
                      <%= f.submit "Registrar",:class=>"waves-effect waves-light btn-large" %>
                  </div>
                </div>
              </form>
  <div >
        <div class="input-field col s6 ">
          <%= button_to "Registro com Facebook", "/auth/facebook", id: "sign_in", :class=>"waves-effect blue darken-4 btn-large"%>
          <%= button_to "Registrar com Gmail", "/auth/google_oauth2",  :class=>"waves-effect  red darken-2 btn-large"%>
          <%= button_to "Registrar com Github", "/auth/github",  :class=>"waves-effect grey darken-4 btn-large"%>
        </div>

  </div>

</div>
</div>




      </div>
    </div>


  </div>









<% end %>

appCastEdu/app/views/users/perfil.html.erb
<div class="row">
  <div class="col s12">
    <div class="card  cyan darken-1 darken-1">
      <div class="card-content white-text">

        <div class="row">
          <div class="col s4 m4">
            <div class="card cyan darken-3 darken-1">
              <div class="card-content white-text">
                <i class="material-icons">assignment_ind</i>
                <span class="card-title">Nome: <%=@user.name %></span>
                <p>Email:    <%=@user.email %></p>
                <p>Categorias de interesse</p>
              </div>
            </div>
          </div>

          <div class="col s m">
            <div class="card cyan darken-3 darken-1">
              <div class="card-content white-text">
                <span class="card-title">Salas que é criador</span>
              <h5>
                      <%=@rooms.count %>
              </h5>

              </div>
            </div>
          </div>

          <div class="col s m">
            <div class="card cyan darken-3 darken-1">
              <div class="card-content white-text">
                <span class="card-title">Salas que participa</span>
              <h5>

              </h5>

              </div>
            </div>
          </div>




        </div>
      </div>


      <div class="card-action">
        <%= button_to "Criar uma Sala", create_room_path(@user.id), id: "sign_in", :class=>"waves-effect waves-light btn-large"%>
      </div>
  <div class="card-action ">
        <ul class="collapsible  " data-collapsible="accordion">
          <% @rooms.each do |room|%>
            <li>
              <div class="collapsible-header cyan darken-2"><i class="material-icons">filter_drama</i>Sala: <%= room.tittle %></div>
              <div class="collapsible-body ">
                  <p>
                    <%= room.description %>
                    <%= button_to "Adicionar um Fórum", create_forum_path(room), :class=>"waves-effect waves-light btn-large right-align "%>
                  </p>


              </div>
            </li>
          <%end%>
       </ul>
  </div>


    </div>
  </div>
</div>

appCastEdu/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user %>

appCastEdu/app/views/users/update_score.html.erb
<!-- Apenas existe para suprir os erros de template do rails  -->