appCastEdu/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'users/perfil/:id' => 'users#get_perfil', as: 'perfil'
  post 'users/profile' => 'users#login', as: 'login'

  get 'room/:id/forum/new' => 'forums#new', as: 'forum'
  post 'room/:id/forum/create' =>'rooms#create_forum', as: 'create_forum'

  match 'auth/:provider/callback' => 'users#register', as: 'register', via: [:get, :post]

  get 'login/' => 'users#index', as: 'make_login'

  post 'users/perfil/:id/create_room'=> 'users#create_room', as: 'create_room'

  resources :admins
  resources :contributors
  resources :comments
  resources :categories

  resources :users

  get  'users/login/:email'  => 'users#login', :constraints => { :email => /[^\/]+/ }
  post 'users/login/:email'  => 'users#login', :constraints => { :email => /[^\/]+/ }
  post 'password_reset/create' => 'password_reset#create'
  get  'password_reset/:key/edit'  => 'password_reset#edit', :constraints => { :email => /[^\/]+/ }
  patch  'password_reset/:key' => 'password_reset#update'

end

appCastEdu/app/models/admin.rb
class Admin < ActiveRecord::Base
end

appCastEdu/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :rooms
end

appCastEdu/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to: entity_colab, :as => :childrenable

end

appCastEdu/app/models/contributor.rb
class Contributor < ActiveRecord::Base
end

appCastEdu/app/models/entity_colab.rb
class EntityColab < ActiveRecord::Base

  has_and_belongs_to_many :children,
      :class_name => "EntityColab",
      :join_table => "children_containers",
      :foreign_key => "container_id",
      :association_foreign_key => "child_id"

    has_and_belongs_to_many :containers,
      :class_name => "EntityColab",
      :join_table => "children_containers",
      :foreign_key => "child_id",
      :association_foreign_key => "container_id"

    def root?
      self.containers.empty?
    end

    def leaf?
      self.children.empty?
    end

    def to_s(level=0)
      "#{'  ' * level}#{name}\n" + children.map {|c| c.to_s(level + 1)}.join
    end


end

appCastEdu/app/models/forum.rb
require "observer"


class Forum < ActiveRecord::Base
    include Observable

    
  belongs_to: entity_colab, :as => :childrenable

  attr_reader :tittle, :description, :room_id, :erros, :forum
  belongs_to :room
  after_initialize :start

  def start
      puts "Inicializando um Forum"
  end

end

appCastEdu/app/models/forum_builder.rb
class ForumBuilder

  attr_reader :tittle, :description, :room

  def initialize room
      if room.class.to_s != 'Room'
          raise StandardError, "Raising standard error"
        end
      @room = room
      @tittle =  'Titulo em Branco'
      @description = 'Insira uma descrição'
  end

  def build_forum
    Forum.new(tittle: @tittle,description: @description, room_id: @room.id).save
  end

  def com_tittle(tittle)
      @tittle = tittle
    self
  end

  def com_description(description)
      @description = description
      self
  end
end

appCastEdu/app/models/room.rb
require "observer"

class Room < ActiveRecord::Base
  include Observable

  has_many: entity_colab, :as => :childrenable
  has_and_belongs_to_many :components


  attr_accessible :tittle, :description,:id,:user_id
  belongs_to :user

    def create_forum
     ForumBuilder.new(self).build_forum
     notify_observer("um novo forum criado ");
    end

   def create_forum tittle, description
     forum =  ForumBuilder.new(self).com_tittle(tittle).com_description(description)
     forum.build_forum
   end

   def feed_users user
     this.add_observer(user)
   end



end

appCastEdu/app/models/room_builder.rb
class RoomBuilder

  attr_reader :tittle, :description, :user

  def initialize user

      if user.class.to_s != 'User'
          raise StandardError, "Raising standard error"
        end
      @user = user
      @tittle =  'Titulo em Branco'
      @description = 'Insira uma descrição'
  end

  def build_room
    puts @user
    room = Room.new(tittle: @tittle,description: @description,user_id: @user.id)
    room.save
  end

  def com_tittle(tittle)
      @tittle = tittle
    self
  end

  def com_description(description)
      @description = description
      self
  end





end

appCastEdu/app/models/session.rb
class Session
  #construtor
  include Singleton

  def _dump(depth)
    # this strips the @strip information from the instance
    Marshal.dump(@keep, depth)
  end

  def self._load(str)
    instance.keep = Marshal.load(str)
    instance
  end


  def initialize session_type,user
    if session_type == "email"
      @session = SessionEmail.new(user)
    else
        @session = SessionSocial.new(user)
    end
        @session.session
        @user = @session.session_user
  end

  def session_user
    @user
  end

  # Metodo Abstrato
  def session
    raise NotImplementedError
  end

end

appCastEdu/app/models/session_email.rb
class SessionEmail < Session

  def initialize user
      @user = user
  end

  def session
    @user.save
    @user = User.find_by_email(session_user.email);
  end

end

appCastEdu/app/models/session_social.rb
class SessionSocial < Session

  def initialize user
      @user = user
  end

  def session
    user = User.new()
      user.email = @user.info.email
      user.name = @user.info.name
      user.password = @user.uid
      user.save
      @user = User.find_by_email(session_user.info.email);
    end
end

appCastEdu/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :idRedeSocial, :id
  has_secure_password
  has_secure_token
  has_many :rooms
   attr_accessible :register
   attr_accessor :register

  validates :email,
            :on => :create,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }

  def register_strategy strategy,user
      Session.new(strategy,user).session_user
  end

  def create_room
    RoomBuilder.new(self).build_room()
  end


end

appCastEdu/app/helpers/admins_helper.rb
module AdminsHelper
end

appCastEdu/app/helpers/categories_helper.rb
module CategoriesHelper
end

appCastEdu/app/helpers/comments_helper.rb
module CommentsHelper
end

appCastEdu/app/helpers/forums_helper.rb
module ForumsHelper
end

appCastEdu/app/helpers/login_helper.rb
module LoginHelper
end

appCastEdu/app/helpers/rooms_helper.rb
module RoomsHelper
end

appCastEdu/app/helpers/users_helper.rb
module UsersHelper
end

appCastEdu/app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

appCastEdu/app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

appCastEdu/app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

appCastEdu/app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

appCastEdu/app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

appCastEdu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A.C.E - APPCASTEDU</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo center">A.C.E - AppCastEdu</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <%= link_to "Login", make_login_path%>
          </li>
          <li>
            <%= link_to "Register", new_user_path%>
          </li>
          <li><a href="collapsible.html">JavaScript</a></li>
        </ul>
      </div>
    </nav>
<%= yield %>

</body>
</html>